import type { ErrorItem } from '../types'

const now = new Date()
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString()

export const sampleItems: ErrorItem[] = [
  {
    id: 'demo-math-1',
    subject: '数学',
    title: '一次方程去括号',
    question: '解方程：2(x - 3) + 5 = 3x - 4。',
    studentAnswer: '2x - 3 + 5 = 3x - 4，x = 6',
    correctAnswer: '2x - 6 + 5 = 3x - 4，解得 x = 3。',
    source: '校内周练',
    grade: '六年级',
    knowledgePoints: ['方程与不等式', '去括号法则'],
    mistakeType: '概念不清',
    rootCause: '去括号时只把 2 乘给了 x，没有同时乘给 -3。',
    explanation: '括号前的系数必须与括号内每一项相乘。第一次偏差发生在 2(x-3)=2x-3 这一步。',
    correctSolution: '2x-6+5=3x-4 → 2x-1=3x-4 → x=3。代回左右两边都等于 5。',
    improvementAdvice: '去括号后立即检查“括号内有几项，乘法就应出现几次”，最后代回验算。',
    tags: ['数学', '方程', '去括号'],
    variants: [
      { question: '解方程：3(x+2)-4=2x+5。', answer: 'x=-1。', hint: '3 要乘括号内的两项。' },
      { question: '解方程：5-2(3-x)=x+1。', answer: 'x=2。', hint: '特别注意括号前是 -2。' },
    ],
    mastered: false,
    reviewCount: 2,
    correctCount: 1,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
    lastReviewedAt: daysAgo(2),
    analysisMode: 'ai',
  },
  {
    id: 'demo-chinese-1',
    subject: '语文',
    title: '现代文句段作用',
    question: '分析文章开头环境描写在全文中的作用。',
    studentAnswer: '写出了天气很冷。',
    correctAnswer: '交代寒冷的环境，烘托人物处境艰难，为下文人物冒雪送书作铺垫，并突出其守信品质。',
    source: '期中复习卷',
    grade: '七年级',
    knowledgePoints: ['现代文阅读', '句段作用'],
    mistakeType: '表达不规范',
    rootCause: '只概括了描写内容，没有结合结构和人物主旨回答“作用”。',
    explanation: '“作用题”至少要区分内容作用与结构作用，并回扣具体文本，不能只翻译句意。',
    correctSolution: '内容：交代寒冷环境、渲染氛围；结构：为下文冒雪送书作铺垫；人物：突出守信。',
    improvementAdvice: '使用“写了什么—结构位置—表现什么”的三格答题框架。',
    tags: ['语文', '现代文', '作用题'],
    variants: [
      { question: '分析结尾再次写到那盏路灯的作用。', answer: '照应开头，深化主旨，并使结构完整。', hint: '结尾优先考虑照应与点题。' },
      { question: '文中画线句运用了景物描写，有何作用？', answer: '结合具体景物，从氛围、人物、情节三方面作答。', hint: '每个术语都要有文本依据。' },
    ],
    mastered: false,
    reviewCount: 1,
    correctCount: 0,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    analysisMode: 'local',
  },
  {
    id: 'demo-english-1',
    subject: '英语',
    title: '现在完成时与 since',
    question: 'He ______ (live) in Shanghai since 2021.',
    studentAnswer: 'lived',
    correctAnswer: 'has lived',
    source: '英语默写',
    grade: '七年级',
    knowledgePoints: ['动词时态', '现在完成时'],
    mistakeType: '审题偏差',
    rootCause: '看到过去时间 2021 就直接使用一般过去时，忽略了 since 表示持续到现在。',
    explanation: 'since + 过去时间点通常与现在完成时连用；主语 He 是第三人称单数，因此用 has lived。',
    correctSolution: 'He has lived in Shanghai since 2021.',
    improvementAdvice: '先圈时间标志词，再判断动作是否延续到现在，最后检查 have/has。',
    tags: ['英语', '时态', 'since'],
    variants: [
      { question: 'She ______ (study) English for five years.', answer: 'has studied', hint: 'for + 时间段，且动作延续至今。' },
      { question: 'They ______ (be) friends since primary school.', answer: 'have been', hint: '主语 They 使用 have。' },
    ],
    mastered: true,
    reviewCount: 3,
    correctCount: 3,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
    lastReviewedAt: daysAgo(1),
    analysisMode: 'ai',
  },
]
